import { useEffect, useState } from "react";
import { db, type Fly, type Post, type Trace } from "./feed";

/**
 * A fly's voice: its post's `trace` (spikes per behaviour-neuron group, every 20 ms, written by the worker) played
 * through Web Audio. Nothing is recorded or generated by AI; every sound follows a neuron group:
 *   wing motor neurons  the buzz, louder and higher when they fire more
 *   escape neurons      a pop (cartoon) or click (realistic) on the steps they fire
 *   grooming neurons    a rustle
 *   steering L / R      pans the sound left or right
 *   forward / backward  bends the pitch up or down
 * The fly's settings give it its own voice: excitability sets the pitch, restlessness the wobble, synapse strength
 * the brightness, and a little from its id so no two flies sound alike. Played SLOW times slower than it happened.
 */
export const SLOW = 2;
export type VoiceStyle = "cartoon" | "real";

const KEY = "flybook-voice";
const listeners = new Set<(s: VoiceStyle) => void>();

function readStyle(): VoiceStyle {
  try {
    return localStorage.getItem(KEY) === "real" ? "real" : "cartoon";
  } catch {
    return "cartoon";
  }
}

/** The viewer's chosen style, shared by every post and remembered in this browser. */
export function useVoiceStyle(): [VoiceStyle, (s: VoiceStyle) => void] {
  const [style, setStyle] = useState<VoiceStyle>(readStyle);
  useEffect(() => {
    listeners.add(setStyle);
    return () => { listeners.delete(setStyle); };
  }, []);
  const change = (s: VoiceStyle) => {
    try {
      localStorage.setItem(KEY, s);
    } catch {
      /* storage blocked: the choice lasts until reload */
    }
    listeners.forEach((l) => l(s));
  };
  return [style, change];
}

/** The post's trace: inline on the demo feed and fresh realtime posts, else fetched on first play. */
export async function loadTrace(post: Post): Promise<Trace | null> {
  if (post.trace) return post.trace;
  if (!db) return null;
  const { data } = await db.from("posts").select("trace").eq("id", post.id).maybeSingle();
  return ((data as { trace?: Trace | null } | null)?.trace) ?? null;
}

let context: AudioContext | null = null;
let noise: AudioBuffer | null = null;

function unit(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0) / 4294967295;
}

/** 0..1 across the episode, so a quiet fly and a loud fly both have a shape. */
function shape(xs: number[]): number[] {
  const lo = Math.min(...xs);
  const hi = Math.max(...xs);
  return xs.map((x) => (hi > lo ? (x - lo) / (hi - lo) : hi > 0 ? 0.5 : 0));
}

function pop(ac: AudioContext, out: AudioNode, at: number, cartoon: boolean, strength: number) {
  const g = ac.createGain();
  g.gain.setValueAtTime(0, at);
  g.connect(out);
  if (cartoon) {
    const o = ac.createOscillator();
    o.type = "sine";
    o.frequency.setValueAtTime(700, at);
    o.frequency.exponentialRampToValueAtTime(2400, at + 0.07);
    g.gain.linearRampToValueAtTime(0.9 * strength, at + 0.01);
    g.gain.exponentialRampToValueAtTime(0.001, at + 0.12);
    o.connect(g);
    o.start(at);
    o.stop(at + 0.13);
  } else {
    const src = ac.createBufferSource();
    src.buffer = noise;
    const hp = ac.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 2500;
    g.gain.linearRampToValueAtTime(0.8 * strength, at + 0.002);
    g.gain.exponentialRampToValueAtTime(0.001, at + 0.02);
    src.connect(hp);
    hp.connect(g);
    src.start(at, Math.random() * 0.5, 0.03);
  }
}

function rustle(ac: AudioContext, out: AudioNode, at: number, length: number, cartoon: boolean, level: number) {
  const src = ac.createBufferSource();
  src.buffer = noise;
  const f = ac.createBiquadFilter();
  f.type = cartoon ? "bandpass" : "lowpass";
  f.frequency.value = cartoon ? 5200 : 2200;
  f.Q.value = cartoon ? 3 : 0.7;
  const g = ac.createGain();
  g.gain.setValueAtTime(0, at);
  g.gain.linearRampToValueAtTime((cartoon ? 0.35 : 0.25) * level, at + length * 0.3);
  g.gain.linearRampToValueAtTime(0, at + length);
  src.connect(f);
  f.connect(g);
  g.connect(out);
  src.start(at, Math.random() * 0.5, length);
}

/** Play a trace; returns a function that stops it. `onEnd` runs once, when it finishes or is stopped. */
export function play(trace: Trace, fly: Fly | undefined, style: VoiceStyle, onEnd: () => void): () => void {
  context ??= new AudioContext();
  const ac = context;
  void ac.resume();
  if (!noise) {
    noise = ac.createBuffer(1, ac.sampleRate, ac.sampleRate);
    const d = noise.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
  }
  const column = (name: string) => {
    const k = trace.groups.indexOf(name);
    return trace.counts.map((row) => (k >= 0 ? row[k] ?? 0 : 0));
  };
  const wing = shape(column("wing"));
  const groom = shape(column("groom"));
  const escape = column("escape");
  const left = column("steer_left");
  const right = column("steer_right");
  const forward = column("forward");
  const backward = column("backward");
  const steps = trace.counts.length;
  const dt = (trace.step_ms / 1000) * SLOW;
  const cartoon = style === "cartoon";
  const t = fly?.temperament ?? {};
  const excitability = Number(t.excitability ?? 1);
  const restlessness = Number(t.restlessness ?? 1);
  const wiring = Number(t.wiring ?? 1);
  const own = 1 + (unit(fly?.id ?? "fly") - 0.5) * 0.25;
  const base = (cartoon ? 460 : 190) * Math.pow(excitability, cartoon ? 3 : 1.2) * own;
  const loud = cartoon ? 0.32 : 0.7;   // rendered test files averaged -23..-44 dB at 0.2 / 0.28

  const t0 = ac.currentTime + 0.05;
  const end = t0 + steps * dt;
  const master = ac.createGain();
  master.gain.setValueAtTime(0, t0);
  master.gain.linearRampToValueAtTime(loud, t0 + 0.03);
  master.gain.setValueAtTime(loud, Math.max(t0 + 0.04, end - 0.08));
  master.gain.linearRampToValueAtTime(0, end);
  master.connect(ac.destination);
  const pan = ac.createStereoPanner();
  pan.pan.setValueAtTime(0, t0);
  pan.connect(master);

  const osc = ac.createOscillator();
  osc.type = cartoon ? "square" : "sawtooth";
  osc.frequency.setValueAtTime(base, t0);
  const tone = ac.createBiquadFilter();
  tone.type = cartoon ? "lowpass" : "bandpass";
  tone.frequency.value = cartoon ? 1600 * wiring : 380 * wiring;
  tone.Q.value = cartoon ? 5 : 1.1;
  const amp = ac.createGain();
  amp.gain.setValueAtTime(0.05, t0);
  osc.connect(tone);
  tone.connect(amp);
  amp.connect(pan);

  const lfo = ac.createOscillator();
  lfo.frequency.value = cartoon ? 4 + 2.5 * restlessness : 11 + 3 * restlessness;   // wobble (cartoon) or wing flutter
  const depth = ac.createGain();
  lfo.connect(depth);
  if (cartoon) {
    depth.gain.value = base * 0.05;
    depth.connect(osc.frequency);
  } else {
    depth.gain.value = 0.12;
    depth.connect(amp.gain);
  }

  for (let s = 0; s < steps; s++) {
    const at = t0 + (s + 1) * dt;
    const bend = Math.max(0.6, 1 + (forward[s] - backward[s]) * (cartoon ? 0.05 : 0.015));
    osc.frequency.linearRampToValueAtTime(base * (1 + (cartoon ? 0.6 : 0.12) * wing[s]) * bend, at);
    amp.gain.linearRampToValueAtTime(0.06 + 0.6 * wing[s], at);
    const turning = left[s] + right[s];
    pan.pan.linearRampToValueAtTime(turning ? Math.max(-0.8, Math.min(0.8, (right[s] - left[s]) / turning)) : 0, at);
    if (escape[s] > 0) pop(ac, master, t0 + s * dt, cartoon, Math.min(1, 0.4 + escape[s] / 4));
    if (groom[s] > 0.35) rustle(ac, pan, t0 + s * dt, dt, cartoon, groom[s]);
  }

  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    onEnd();
  };
  osc.onended = finish;
  osc.start(t0);
  lfo.start(t0);
  osc.stop(end + 0.02);
  lfo.stop(end + 0.02);
  return () => {
    if (done) return;
    const now = ac.currentTime;
    master.gain.cancelScheduledValues(now);
    master.gain.setValueAtTime(0, now);
    try {
      osc.stop(now + 0.01);
      lfo.stop(now + 0.01);
    } catch {
      /* already stopped */
    }
    finish();
  };
}
